# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 05:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=255)),
                ('parentid', models.CharField(blank=True, max_length=10, null=True)),
                ('kind', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('budget_account', models.BooleanField(default=True)),
                ('loading_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['company', 'account_id'],
            },
        ),
        migrations.CreateModel(
            name='AccountsTransactions',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=15)),
                ('center_id', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loading_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['company', 'transaction_date', 'account_id'],
            },
        ),
        migrations.CreateModel(
            name='AccountsTypes',
            fields=[
                ('account_type_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('account_type_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Accounts Types',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan_budget_amount', models.PositiveIntegerField(default=0)),
                ('feb_budget_amount', models.PositiveIntegerField(default=0)),
                ('mar_budget_amount', models.PositiveIntegerField(default=0)),
                ('apr_budget_amount', models.PositiveIntegerField(default=0)),
                ('may_budget_amount', models.PositiveIntegerField(default=0)),
                ('jun_budget_amount', models.PositiveIntegerField(default=0)),
                ('jul_budget_amount', models.PositiveIntegerField(default=0)),
                ('aug_budget_amount', models.PositiveIntegerField(default=0)),
                ('sep_budget_amount', models.PositiveIntegerField(default=0)),
                ('oct_budget_amount', models.PositiveIntegerField(default=0)),
                ('nov_budget_amount', models.PositiveIntegerField(default=0)),
                ('dec_budget_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[['d', 'Draft'], ['s', 'Saved'], ['a', 'Approved']], default='d', max_length=1)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budget - Accounts',
                'ordering': ['company', 'year_id', 'account_id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetYear',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[['d', 'Draft'], ['a', 'Active'], ['c', 'Closed']], default='d', max_length=1)),
            ],
            options={
                'verbose_name': 'Budget Year',
                'ordering': ['year'],
                'verbose_name_plural': 'Budget - Years',
            },
        ),
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('center_id', models.CharField(max_length=10)),
                ('center_name', models.CharField(max_length=255)),
                ('parentid', models.CharField(blank=True, max_length=10, null=True)),
                ('kind', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('loading_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Center',
                'verbose_name_plural': 'Centers',
                'ordering': ['company', 'center_id'],
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='CompaniesLogos')),
            ],
            options={
                'verbose_name': 'Company',
                'ordering': ['company_id'],
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='EtlLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('type_id', models.CharField(choices=[['Accounts', 'Accounts'], ['Centers', 'Centers'], ['Transactions', 'Transactions'], ['HR', 'HR']], max_length=30)),
                ('company', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ETL Log',
                'verbose_name_plural': 'ETL Logs',
                'ordering': ['log_time', 'type_id', 'company'],
            },
        ),
        migrations.CreateModel(
            name='EtlSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[['a', 'Accounts'], ['c', 'Centers'], ['t', 'Transactions'], ['h', 'HR']], max_length=1)),
                ('schedule_time', models.CharField(choices=[['00', '00:00'], ['01', '01:00'], ['02', '02:00'], ['03', '03:00'], ['04', '04:00'], ['05', '05:00'], ['06', '06:00'], ['07', '07:00'], ['08', '08:00'], ['09', '09:00'], ['10', '10:00'], ['11', '11:00'], ['12', '12:00'], ['13', '13:00'], ['14', '14:00'], ['15', '15:00'], ['16', '16:00'], ['17', '17:00'], ['18', '18:00'], ['19', '19:00'], ['20', '20:00'], ['21', '21:00'], ['22', '22:00'], ['23', '23:00']], max_length=2)),
            ],
            options={
                'verbose_name': 'ETL Schedule',
                'verbose_name_plural': 'ETL Schedule',
                'ordering': ['data_type', 'schedule_time'],
            },
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('center_id', models.CharField(max_length=10)),
                ('employee_id', models.CharField(max_length=15)),
                ('employee_name', models.CharField(max_length=200)),
                ('employment_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField()),
                ('loading_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Companies')),
            ],
            options={
                'verbose_name': 'HR',
                'verbose_name_plural': 'HR',
                'ordering': ['company', 'center_id', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='HRBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_count', models.PositiveIntegerField(verbose_name='Staff Budget')),
                ('status', models.CharField(choices=[['d', 'Draft'], ['s', 'Saved'], ['a', 'Approved']], default='d', max_length=1)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Centers', verbose_name='Cost Center')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Companies')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.BudgetYear', verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budget - HR',
                'ordering': ['company', 'year_id', 'center'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Role',
                'permissions': (('landing_page', 'Can  view landing'), ('acc_trends', 'Can  view trends accounts'), ('mrg_exp_rev', 'Can  view margin expenses and revenues KPI'), ('budget', 'Can  view budget KPI')),
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UsersCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Companies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Company',
                'verbose_name_plural': 'Users Companies',
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='UsersSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='UsersPhotos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'Users Settings',
                'ordering': ['user'],
            },
        ),
        migrations.AddIndex(
            model_name='etlschedule',
            index=models.Index(fields=['data_type'], name='analytics_e_data_ty_150577_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etlschedule',
            unique_together=set([('data_type', 'schedule_time')]),
        ),
        migrations.AddIndex(
            model_name='etllog',
            index=models.Index(fields=['type_id'], name='analytics_e_type_id_ad083e_idx'),
        ),
        migrations.AddIndex(
            model_name='etllog',
            index=models.Index(fields=['company'], name='analytics_e_company_baad15_idx'),
        ),
        migrations.AddField(
            model_name='centers',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Companies'),
        ),
        migrations.AddField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Accounts', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='budget',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Centers', verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Companies'),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.BudgetYear', verbose_name='Year'),
        ),
        migrations.AlterUniqueTogether(
            name='accountstypes',
            unique_together=set([('account_type_name',)]),
        ),
        migrations.AddField(
            model_name='accountstransactions',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Companies'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.AccountsTypes'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Companies'),
        ),
        migrations.AddIndex(
            model_name='userssettings',
            index=models.Index(fields=['user'], name='analytics_u_user_id_305c5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userssettings',
            unique_together=set([('user',)]),
        ),
        migrations.AddIndex(
            model_name='userscompanies',
            index=models.Index(fields=['company'], name='analytics_u_company_abbe9a_idx'),
        ),
        migrations.AddIndex(
            model_name='userscompanies',
            index=models.Index(fields=['user'], name='analytics_u_user_id_14770f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userscompanies',
            unique_together=set([('company', 'user')]),
        ),
        migrations.AddIndex(
            model_name='hrbudget',
            index=models.Index(fields=['company'], name='analytics_h_company_089819_idx'),
        ),
        migrations.AddIndex(
            model_name='hrbudget',
            index=models.Index(fields=['year'], name='analytics_h_year_id_bd94e6_idx'),
        ),
        migrations.AddIndex(
            model_name='hrbudget',
            index=models.Index(fields=['center'], name='analytics_h_center__42bb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='hrbudget',
            index=models.Index(fields=['status'], name='analytics_h_status_bb9191_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hrbudget',
            unique_together=set([('company', 'year', 'center')]),
        ),
        migrations.AddIndex(
            model_name='hr',
            index=models.Index(fields=['company'], name='analytics_h_company_e58359_idx'),
        ),
        migrations.AddIndex(
            model_name='hr',
            index=models.Index(fields=['center_id'], name='analytics_h_center__72c51b_idx'),
        ),
        migrations.AddIndex(
            model_name='hr',
            index=models.Index(fields=['status'], name='analytics_h_status_6bc0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='hr',
            index=models.Index(fields=['employee_id'], name='analytics_h_employe_8d1607_idx'),
        ),
        migrations.AddIndex(
            model_name='hr',
            index=models.Index(fields=['employment_date'], name='analytics_h_employm_047e88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hr',
            unique_together=set([('company', 'employee_id')]),
        ),
        migrations.AddIndex(
            model_name='centers',
            index=models.Index(fields=['company'], name='analytics_c_company_029596_idx'),
        ),
        migrations.AddIndex(
            model_name='centers',
            index=models.Index(fields=['center_id'], name='analytics_c_center__d5c440_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['company'], name='analytics_b_company_dfa2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['year'], name='analytics_b_year_id_a3dc30_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['account'], name='analytics_b_account_d17293_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['center'], name='analytics_b_center__3fc3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['status'], name='analytics_b_status_793e90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set([('company', 'year', 'account', 'center')]),
        ),
        migrations.AddIndex(
            model_name='accountstransactions',
            index=models.Index(fields=['company'], name='analytics_a_company_cfe934_idx'),
        ),
        migrations.AddIndex(
            model_name='accountstransactions',
            index=models.Index(fields=['account_id'], name='analytics_a_account_3a4f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountstransactions',
            index=models.Index(fields=['transaction_date'], name='analytics_a_transac_c55a08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountstransactions',
            unique_together=set([('company', 'account_id', 'transaction_date', 'center_id')]),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['company'], name='analytics_a_company_4ae101_idx'),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['account_id'], name='analytics_a_account_336233_idx'),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['account_type'], name='analytics_a_account_eb7084_idx'),
        ),
    ]
