# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_auto_20171118_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='kind',
            field=models.NullBooleanField(default=False),
        ),
    ]
