# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_auto_20171118_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiconfiguration',
            name='account',
        ),
        migrations.RemoveField(
            model_name='kpiconfiguration',
            name='company',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='kind',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='parentid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountstypes',
            name='account_type_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='account type id'),
        ),
        migrations.AlterField(
            model_name='accountstypes',
            name='account_type_name',
            field=models.CharField(max_length=100, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='apr_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Apr'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='aug_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Aug'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='dec_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Dec'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='feb_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Feb'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='jan_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Jan'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='jul_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Jul'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='jun_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Jun'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='mar_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Mar'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='may_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='nov_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Nov'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='oct_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Oct'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='sep_budget_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Sep'),
        ),
        migrations.DeleteModel(
            name='KpiConfiguration',
        ),
    ]
