# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_auto_20171130_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(choices=[['t', 'Tax'], ['z', 'Zaka'], ['d', 'Depreciation']], max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Accounts')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Companies')),
            ],
            options={
                'ordering': ['company', 'type_id'],
                'verbose_name_plural': 'KPIs Accounts Settings',
                'verbose_name': 'KPI Account Setting',
            },
        ),
    ]
