# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_kpiaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(choices=[['o', 'Operation Cost Centers']], max_length=1)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Centers')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Companies')),
            ],
            options={
                'verbose_name': 'KPI Cost Center Setting',
                'verbose_name_plural': 'KPIs Centers Settings',
                'ordering': ['company', 'type_id'],
            },
        ),
    ]
