# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_kpicenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpicenter',
            options={'ordering': ['company', 'type_id'], 'verbose_name': 'KPI Cost Center', 'verbose_name_plural': 'KPIs Cost Centers Settings'},
        ),
    ]
