# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_auto_20171204_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssettings',
            name='language',
            field=models.CharField(choices=[['en', 'English'], ['ar', 'عربي']], default='en', max_length=2),
        ),
    ]
