# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesbudget',
            name='status',
            field=models.CharField(blank=True, choices=[['s', 'Saved'], ['d', 'Draft'], ['a', 'Approved']], default='d', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersactivities',
            name='status',
            field=models.CharField(blank=True, choices=[['o', 'Open'], ['c', 'Closed']], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersactivitiesactions',
            name='action_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 16, 37, 29, 674460, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customersactivitiesactions',
            name='status',
            field=models.CharField(blank=True, choices=[['o', 'Open'], ['c', 'Closed']], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersstatus',
            name='rate',
            field=models.CharField(blank=True, choices=[['e', 'Excellent'], ['n', 'Not Rated'], ['v', 'V.Good'], ['g', 'Good'], ['a', 'Accepted']], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersstatus',
            name='status',
            field=models.CharField(blank=True, choices=[['n', 'New'], ['r', 'Archived'], ['d', 'Dormant'], ['a', 'Active']], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='industriesbudget',
            name='status',
            field=models.CharField(blank=True, choices=[['s', 'Saved'], ['d', 'Draft'], ['a', 'Approved']], default='d', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='status',
            field=models.CharField(blank=True, choices=[['o', 'Open'], ['m', 'Missed'], ['s', 'Success']], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='salesagentsbudget',
            name='status',
            field=models.CharField(blank=True, choices=[['s', 'Saved'], ['d', 'Draft'], ['a', 'Approved']], default='d', max_length=1, null=True),
        ),
    ]
