# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 19:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_auto_20180123_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriesbudget',
            name='status',
            field=models.CharField(blank=True, choices=[['d', 'Draft'], ['a', 'Approved'], ['s', 'Saved']], default='d', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersactivities',
            name='status',
            field=models.CharField(blank=True, choices=[['c', 'Closed'], ['o', 'Open']], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersactivitiesactions',
            name='action_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 19, 43, 37, 989205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customersactivitiesactions',
            name='status',
            field=models.CharField(blank=True, choices=[['c', 'Closed'], ['o', 'Open']], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersstatus',
            name='rate',
            field=models.CharField(blank=True, choices=[['v', 'V.Good'], ['n', 'Not Rated'], ['e', 'Excellent'], ['a', 'Accepted'], ['g', 'Good']], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='industriesbudget',
            name='status',
            field=models.CharField(blank=True, choices=[['d', 'Draft'], ['a', 'Approved'], ['s', 'Saved']], default='d', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='salesagentsbudget',
            name='status',
            field=models.CharField(blank=True, choices=[['d', 'Draft'], ['a', 'Approved'], ['s', 'Saved']], default='d', max_length=1, null=True),
        ),
    ]
