# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180127_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunities',
            options={'permissions': (('Add_Opportunity', 'Can  Add Opportunity'), ('Update_Opportunity', 'Can uUpdate Opportunity')), 'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterField(
            model_name='categoriesbudget',
            name='status',
            field=models.CharField(blank=True, choices=[['a', 'Approved'], ['s', 'Saved'], ['d', 'Draft']], default='d', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersactivities',
            name='status',
            field=models.CharField(blank=True, choices=[['c', 'Closed'], ['o', 'Open']], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersactivitiesactions',
            name='action_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 14, 45, 38, 513503, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customersactivitiesactions',
            name='status',
            field=models.CharField(blank=True, choices=[['c', 'Closed'], ['o', 'Open']], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersstatus',
            name='rate',
            field=models.CharField(blank=True, choices=[['n', 'Not Rated'], ['a', 'Accepted'], ['v', 'V.Good'], ['g', 'Good'], ['e', 'Excellent']], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customersstatus',
            name='status',
            field=models.CharField(blank=True, choices=[['n', 'New'], ['a', 'Active'], ['d', 'Dormant'], ['r', 'Archived']], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='industriesbudget',
            name='status',
            field=models.CharField(blank=True, choices=[['a', 'Approved'], ['s', 'Saved'], ['d', 'Draft']], default='d', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='status',
            field=models.CharField(blank=True, choices=[['s', 'Success'], ['m', 'Missed'], ['o', 'Open']], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='salesagentsbudget',
            name='status',
            field=models.CharField(blank=True, choices=[['a', 'Approved'], ['s', 'Saved'], ['d', 'Draft']], default='d', max_length=1, null=True),
        ),
    ]
